package activities;

public enum ActivityLocation {
	HOME_LOCATION,
	WORK_PLACE_LOCATION,
	THIRD_WORK_PLACE_LOCATION,
	LEISURE_LOCATION,
	THIRD_LEISURE_LOCATION,
	THIRD_HOUSEHOLD_CARE_LOCATION,
	TRAVEL
}
